### ISSUE TITLE
Implement details as discussed

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-model-migration#14]
- The names of the new schematisations: ({Repo name} - {sqlite path} - {settings name} ({settings id}))
- Create list of non-referenced tiff files
- Revert the revision_nr + 1 logic (we keep the mercurial numbers)
- Filter 3Di v1 models, models of organisations without contract (@Jonasvsl supplies list), testbank

**Comment by Jonasvsl** [comment]
I have a list for revision at Linda at the moment

**Comment by caspervdw** [comment]
Sure. Keep in mind this is a public repo before posting the list ;)

**Comment by Jonasvsl** [comment]
Ok, then maybe I shouldn't post it in github
